-- QUESTÃO 04
CREATE PROCEDURE AdicionarEstado
AS
BEGIN
	IF EXISTS (SELECT Estado FROM Edificios WHERE E1200 = 1 OR E1200 IS NULL)
		BEGIN
			INSERT INTO Edificios(Id, Estado) VALUES(NEWID(), 1)
		END
	ELSE IF EXISTS (SELECT Estado FROM Edificios WHERE E1200 = 1)
		BEGIN
			INSERT INTO Edificios(Id, Estado) VALUES(NEWID(), 2)
		END
	ELSE IF EXISTS (SELECT Estado FROM Edificios WHERE E1100 = 1 AND E1200 = 1)
		BEGIN
			INSERT INTO Edificios(Id, Estado) VALUES(NEWID(), 3)
		END
END